sudo: false
language: java
notifications:
  email: false
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install: wget https://gist.githubusercontent.com/Doridian/01cb63301fe4d022f533bd221e227970/raw/0771d2c50808b295abfbabe266be7368c3273974/settings.xml
  -O settings.bin
script: mvn deploy -DaltDeploymentRepository=deployment-repo-id::default::https://maven.doridian.net/repository/maven-snapshots/
  --settings settings.bin
env:
  global:
  - secure: Zsg4mprRwMI0o3y+4CxQvk9eHgwek8X8DZOBJfu4k9ZDtK9WAZoIGhbQluuW22CB/G2OVyHlTw5pKScAKqwRGNDEO68TQ5ThuQujhXywlGEW+9WyTWipYH6EqZfyvXkuAbeVZO5+B0QnMyomxKHPsqIeu4LlFtytxOxV+X6bCuj08C1JMG9HWWx7LZE7o7tNqceqItifGZZj2MsMfDhJ1LS6vp1oyXuyPdytgSiWD2ZFkqTecb4s0slC4qb66kwQ4Ju33KgvGmd4BCuZzh3yLAO07j0bwpcBYQT7ORoehiwljb6D/gxDhLwhqSMTeczI9AcN2HSsV5dc9uv63y3wzAx6v+k62QG5iJhzTEJLKVDYRl/Xci5PrzGQ5is7CoNYpcRI0hgLZZHxpDbaA4XADkzJeukr5Fgp6rE49Dtg7apJHGwlrQjSgvzLQGfcMSk/Ubj1CTgqwWZRj9i0hPjPCYteN8k8JHqBa8+AKtcpfdhX+1dC8xW1XWj/3C3PWEWR+uhjo2adfmaUfjamDWwHB3M/S0WDcO9BZIwYdHoHzcL6iZv5+bDZdmLu3PBeJk8gR0nI9giq5zIqvAXYV/3f3DKDrgqmGCdRQlnpy6Ed7luyuGLWkhcqJyUgwL3q0Gh/i7Ub8so0tDLAjh+81rp29q35b6HHz6PnR3RDR3oNVHQ=
  - secure: DjlTKqKmpEj1hXq+/AhBKIr8nUfm2PW0UGL+Gtrvn09BYVW11ZRD3ZOy+IeORE++Cyu5Mh7EWto+FrBwD1RKdMxe8kGb8q5UnuZszi3IZ0QY4SEpGMWlKmxsUPuROAuXS4QRIjGfghIErzRPPO1/uJSaX69JRlsG04GlYoO2tv4HHvsx2f2n1+vuNhxMWNkV58mVa5zAvxI8Ky3JyGRN/K8rCeXWjmOu+Jti4qnECYMfsD92ceYuDoBsNOihTvyi5IZaWKEvh/BzPqr49GPyYEbbrmSC2Src/0E4N3YVKPAAvxf+bk3GAcJ877qMn/hOolkEUmNnziKetm9GWb2Qz+wEUe6JM53wZTK1aSCxj/b3PTYXOl8L51cpOXUXkaP9AOn0aDAyN7VVQRS2RIXTZP8vPjF1DS3vxclJLDXC07j1zzie8QyasF9IYJ9THI/F4k7yx16sO0/D1ZmfVSYxTkjMMInYplpZuGbDYyQhFzEsCSatHUUvijKrHaCLDsT3Wf4oe6on2kZ4t15cHyqU/LS+s4scXPZS9A3TWl41Uhg8POXR99ZrjW8FbmeCrgBzxcksnrxaPjupBD3jWfeNJ72lLCbasdQAKEtEqWYr6aR7rDy5lr7yyXMFHarjuDdX6VbZPPvQiCJY3cp8SLIU0gmMUgyXcZIcDybAr0fjv5E=
