name: FoxBukkitCheckoff
main: com.foxelbox.foxbukkit.checkoff.FoxBukkitCheckoff
version: 1.0.0
depend: [FoxBukkitChat, FoxBukkitScoreboard, FoxBukkitPermissions, LogBlock]
commands:
  co:
    description: Uses Checkoff system
    permission: foxbukkit.checkoff.co
    usage: /<command>